# Generated by Django 4.0.4 on 2022-05-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='institute_email',
            field=models.EmailField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
