# Generated by Django 4.0.4 on 2022-05-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='hello', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
