# Generated by Django 3.1.6 on 2021-02-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('google_uid', models.CharField(max_length=15)),
                ('institute_email', models.EmailField(max_length=28, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
            ],
        ),
    ]
