# Generated by Django 3.1.6 on 2021-03-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='google_uid',
            field=models.CharField(max_length=28),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='institute_email',
            field=models.EmailField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
