# Generated by Django 4.0.4 on 2022-05-29 21:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=100)),
                ('semester', models.CharField(choices=[('autumn', 'Autumn'), ('winter', 'Winter')], default='autumn', max_length=6)),
                ('academic_year', models.CharField(choices=[('2022-2023', '2022-2023'), ('2021-2022', '2021-2022'), ('2020-2021', '2020-2021')], default='2022-2023', max_length=9)),
                ('start_timestamp', models.DateTimeField()),
                ('attendance_duration_in_minutes', models.IntegerField(default=5)),
                ('instructors', models.ManyToManyField(blank=True, related_name='instructors', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(blank=True, related_name='students', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('course_code', 'semester', 'academic_year'), name='course_unique_per_sem_per_year'),
        ),
    ]
