# Generated by Django 3.1.6 on 2021-03-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=8)),
                ('course_name', models.CharField(max_length=70)),
                ('semester', models.CharField(choices=[('autumn', 'Autumn'), ('winter', 'Winter')], default='autumn', max_length=6)),
                ('academic_year', models.CharField(choices=[], default='2020-2021', max_length=9)),
                ('instructor_name', models.CharField(max_length=40)),
                ('start_timestamp', models.DateTimeField()),
            ],
        ),
    ]
