# Generated by Django 3.1.6 on 2021-02-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=70)),
                ('instructor_name', models.CharField(max_length=34)),
            ],
        ),
    ]
