# Generated by Django 4.0.4 on 2022-05-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='start_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
