# Generated by Django 3.1.6 on 2021-03-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='academic_year',
            field=models.CharField(choices=[('2021-2022', '2021-2022'), ('2020-2021', '2020-2021')], default='2020-2021', max_length=9),
        ),
    ]
