# Generated by Django 3.1.6 on 2021-02-14 18:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='attendance_window',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='course',
            name='start_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 14, 18, 33, 35, 277595, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor_name',
            field=models.CharField(max_length=40),
        ),
    ]
