# Generated by Django 4.0.4 on 2022-05-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_start_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='start_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
