# Generated by Django 3.1.6 on 2021-03-09 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_remove_faculty_course'),
        ('course', '0002_auto_20210310_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor_name',
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty'),
        ),
        migrations.AlterField(
            model_name='course',
            name='academic_year',
            field=models.CharField(choices=[('2021-2022', '2021-2022'), ('2020-2021', '2020-2021')], default=('2021-2022', '2021-2022'), max_length=9),
        ),
    ]
