# Generated by Django 3.1.6 on 2021-02-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20210215_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='start_timestamp',
            field=models.DateTimeField(),
        ),
    ]
