# Generated by Django 3.1.6 on 2021-03-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20210310_0107'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('course_code', 'semester', 'academic_year'), name='course_unique_per_sem_per_year'),
        ),
    ]
