# Generated by Django 3.1.6 on 2021-03-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20210319_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='attendance_duration',
            field=models.IntegerField(default=30),
        ),
    ]
