# Generated by Django 4.0.5 on 2022-06-16 06:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_alter_course_course_student_mapper_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_student_mapper_file',
            field=models.FileField(blank=True, null=True, upload_to='student_mapper_csv/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])]),
        ),
    ]
