# Generated by Django 3.1.6 on 2021-03-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='institute_email',
            field=models.EmailField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
