# Generated by Django 3.1.6 on 2021-03-09 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_auto_20210310_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='course',
        ),
    ]
