# Generated by Django 3.1.6 on 2021-03-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_remove_faculty_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='access_token',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
