# Generated by Django 3.1.6 on 2021-03-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_faculty_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='access_token',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
