# Generated by Django 3.1.6 on 2021-03-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_auto_20210310_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='institute_email',
            field=models.EmailField(default='test@test.com', max_length=40, primary_key=True, serialize=False),
        ),
    ]
