# Generated by Django 4.0.4 on 2022-06-09 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0002_accesspoint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessPoint',
        ),
    ]
