# Generated by Django 3.1.6 on 2021-02-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0002_metadata_min_app_build'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadata',
            name='id',
        ),
        migrations.AlterField(
            model_name='metadata',
            name='min_app_build',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
