# Generated by Django 3.1.6 on 2021-02-13 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0003_auto_20210210_0729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metadata',
            options={'ordering': ['-min_app_build']},
        ),
    ]
