# Generated by Django 4.0.5 on 2022-06-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0003_delete_accesspoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apk_download', models.URLField(default='')),
                ('ios_download', models.URLField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
