# Generated by Django 4.0.5 on 2022-06-16 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0004_downloadlinks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DownloadLinks',
            new_name='DownloadLink',
        ),
    ]
