# Generated by Django 4.0.4 on 2022-05-31 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('model', models.CharField(default='', max_length=50)),
                ('brand', models.CharField(default='', max_length=20)),
                ('device_id', models.CharField(default='', max_length=50)),
                ('device_name', models.CharField(default='', max_length=100)),
                ('is_physical', models.BooleanField(default=True)),
                ('is_rooted', models.BooleanField(default=False)),
                ('app_version_string', models.CharField(max_length=10)),
                ('app_build_number', models.IntegerField()),
                ('ssid', models.CharField(max_length=32)),
                ('bssid', models.CharField(max_length=23)),
                ('local_ip', models.GenericIPAddressField()),
                ('server_key', models.CharField(max_length=40)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
