# Generated by Django 3.1.6 on 2021-02-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='server_key',
            field=models.CharField(default='default-hash', max_length=40),
            preserve_default=False,
        ),
    ]
