# Generated by Django 4.0.4 on 2022-06-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_remove_registration_server_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='os',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='os_version',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
    ]
