# Generated by Django 3.1.1 on 2021-02-12 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_registration_server_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['-timestamp']},
        ),
    ]
