# Generated by Django 3.1.6 on 2021-02-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_registration_server_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('server_key', models.CharField(max_length=40)),
                ('institute_email', models.EmailField(max_length=28, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['-timestamp']},
        ),
    ]
