# Generated by Django 4.0.4 on 2022-06-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_registration_os_registration_os_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='bssid',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='device_id',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='registration',
            name='device_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='registration',
            name='model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='os',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='os_version',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='registration',
            name='ssid',
            field=models.CharField(max_length=50),
        ),
    ]
