# Generated by Django 3.1.6 on 2021-02-13 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20210213_1451'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Verification',
        ),
    ]
