# Generated by Django 4.0.4 on 2022-06-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_registration_brand_alter_registration_bssid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='bssid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='ssid',
            field=models.CharField(max_length=100),
        ),
    ]
