# Generated by Django 4.0.4 on 2022-06-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_alter_registration_bssid_alter_registration_ssid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='os_version',
            field=models.CharField(max_length=100),
        ),
    ]
