# Generated by Django 4.0.4 on 2022-05-30 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_course_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={'ordering': ('-created_at',)},
        ),
    ]
