# Generated by Django 3.1.6 on 2021-02-10 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device_id', models.CharField(max_length=16)),
                ('is_physical', models.BooleanField(default=True)),
                ('is_rooted', models.BooleanField(default=False)),
                ('fingerprint', models.CharField(max_length=150)),
                ('sdk_int', models.IntegerField()),
                ('app_version_string', models.CharField(max_length=10)),
                ('app_build_number', models.IntegerField()),
                ('ssid', models.CharField(max_length=32)),
                ('bssid', models.CharField(max_length=23)),
                ('local_ip', models.GenericIPAddressField()),
                ('attendance_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('server_key', models.CharField(max_length=40)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('student_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentdata')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
