# Generated by Django 3.1.6 on 2021-03-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='ble_verifications_count',
            field=models.IntegerField(default=0),
        ),
    ]
