# Generated by Django 3.1.6 on 2021-03-22 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20210314_0012'),
        ('attendance', '0002_attendance_ble_verifications_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='ble_verifications_count',
        ),
        migrations.CreateModel(
            name='BleVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('verified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentdata')),
                ('verified_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.attendance')),
            ],
        ),
        migrations.AddConstraint(
            model_name='bleverification',
            constraint=models.UniqueConstraint(fields=('verified_by', 'verified_for'), name='unique_verification_per_attendance'),
        ),
    ]
