# Generated by Django 3.1.6 on 2021-03-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20210322_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bleverification',
            name='verified_by',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='bleverification',
            name='verified_for',
            field=models.IntegerField(),
        ),
    ]
