# Generated by Django 4.0.4 on 2022-06-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendance_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
