# Generated by Django 4.0.5 on 2022-06-16 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_attendance_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-id']},
        ),
    ]
